# Generated by Django 5.2.1 on 2025-08-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.TextField(max_length=400)),
                ('dataPublicao', models.DateField(default='2025-01-01')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
            ],
        ),
    ]
