# Generated by Django 5.2.1 on 2025-08-04 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Não concluída', 'Não concluída'), ('Concluída', 'Concluída')], default='Não concluída', max_length=13)),
                ('prazo', models.DateField(default=datetime.date(2025, 8, 4))),
            ],
        ),
    ]
